### ISSUE TITLE
Script won't run when snpid=variant id

### ISSUE THREAD

**Issue by tjmeyers** [omeed-maghzian/mtag#12]
Hi, 

I successfully ran your script with snpid=rs number. However, in my data, rsid is non-unique, while variant (chr:pos:a1:a2) is unique. Unfortunately, the script would not run when I used this as the input snpid. First, I left rsid in the data (with snpid=variant) but the script said 2 SNP columns were detected, and the program stopped. Next, I removed rsid, but the program returned this error: "After merging with reference panel LD, 0 SNPs remain." Any advice? Thanks.

**Comment by tjmeyers** [comment]
Oh I see you addressed this in a closed issue. Thanks.

**Comment by tjmeyers** [comment]
Just fyi, my data only includes autosomal SNP's, not sex chromosomal SNP's.

**Comment by omeed-maghzian** [comment]
Hi Travis, 

The errors during MTAG's call of `ldsc` to compute the residual covariance matrix (Sigma). The default LD Score reference panel is [this one](https://data.broadinstitute.org/alkesgroup/LDSCORE/eur_w_ld_chr.tar.bz2), also referenced in the ldsc tutorial [here](https://github.com/bulik/ldsc/wiki/LD-Score-Estimation-Tutorial). The rsid needs to be unique because that is the column used to merge in the LD reference panel.

The best approach would be to find the appropriate chr:pos:a1:a2-to-rsid mapping that would let you use the default LD reference panel file. 

Alternatively, you could also construct your own LD scores and pass those to MTAG but, given the effort, it is probably not recommended.
