### ISSUE TITLE
Allow MTAG to accept beta / se columns (instead of z, n)

### ISSUE THREAD

**Issue by omeed-maghzian** [omeed-maghzian/mtag#13]
@paturley I am posting your comment on allowing MTAG to accept beta / se  columns from #10 

> it would be good if we could add an option to MTAG so it
accepts betas and SEs rather than Zs and Ns. It would be a lot more robust
to these sorts of problems.

Would we then back out the approximate sample from the z(=beta/se) and use that in the summary table and output of results?

**Comment by paturley** [comment]
I would report still report the N that is input into the software (if
available) but I would just use the SE for the calculation. Does that make
sense?

**Comment by omeed-maghzian** [comment]
So I guess we would:
* report N / effective N from using the provided N column
* use SE for the MTAG weights 

Questions:
1) Do you mean that sigma_j is now going to be weighted by SE instead of 1/sqrt(N)? Wouldn't we still need to figure out whether the SE has been standardized in order to avoid applying the genotype standardization after computing the MTAG results? 
2) Does that mean that when BETA/SE is included, the sample size is no longer strictly required by MTAG (though it could be highly suggested)?

**Comment by paturley** [comment]
1. Yes. If we use BETA/SE, then we will first need to transform both so
they are in standardized units. This way, we can replace 1/sqrt(N) with SE
pretty much everywhere in the code.
2. Yes. N would still be required to run LDSC though right? I suppose it
would make sense actually to pass in 1/SE^2 instead of N to LDSC instead so
we are internally consistent. Would that be hard?

**Comment by huilisabrina** [comment]
Hi @omeed-maghzian ,

Just to follow up on #26 , could you add an input checker for the `beta` `se`, so that the user can understand more easily what they are missing? Right now the error messages are somewhat counter-intuitive. It'd be helpful to add clearer messages. Below is the tracebacks for your reference:

- In the case where beta is present but se is missing: 
```
Traceback (most recent call last):
  File "mtag/mtag.py", line 1357, in <module>
    mtag(args)
  File "mtag/mtag.py", line 1198, in mtag
    DATA, args = load_and_merge_data(args)
  File "mtag/mtag.py", line 237, in load_and_merge_data
    GWAS_d[p], sumstats_format[p] = _perform_munge(args, GWAS_d[p], gwas_dat_gen, p)
  File "mtag/mtag.py", line 135, in _perform_munge
    GWAS_df['z'] = GWAS_df[args.beta_name] / GWAS_df[args.se_name]
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 1997, in __getitem__
    return self._getitem_column(key)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 2004, in _getitem_column
    return self._get_item_cache(key)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/generic.py", line 1350, in _get_item_cache
    values = self._data.get(item)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/internals.py", line 3299, in get
    raise ValueError("cannot label index with a null key")
ValueError: cannot label index with a null key 
```
- In the case where se is present but beta is missing:
```
Traceback (most recent call last):
  File "mtag/mtag.py", line 1357, in <module>
    mtag(args)
  File "mtag/mtag.py", line 1198, in mtag
    DATA, args = load_and_merge_data(args)
  File "mtag/mtag.py", line 237, in load_and_merge_data
    GWAS_d[p], sumstats_format[p] = _perform_munge(args, GWAS_d[p], gwas_dat_gen, p)
  File "mtag/mtag.py", line 157, in _perform_munge
    munged_results = munge_sumstats.munge_sumstats(argnames, write_out=False, new_log=False)
  File "/disk/genetics/ukb/huili/mtag/mtag/ldsc_mod/munge_sumstats.py", line 639, in munge_sumstats
    raise ValueError('Could not find {C} column.'.format(C=c))
ValueError: Could not find SIGNED_SUMSTAT column. 
```
Also I think the latest `v1.0.8` takes BETA and SE from the sumstats to calculate the Z’s, but still relies on the N for weighting. This doesn’t seem to align with the conclusions above, so just wanted flag that as well. 

Also, I have a modified version of the munge_sumstats that filters based on BETA and SE (so those columns are present in the munged output). Do you think it is worthwhile integrating that with the current MTAG? It’ll make the sumstats reading + cleaning more consistent, but not a very big deal. 

Thanks,
Hui

**Comment by huilisabrina** [comment]
This option was added via the [commit](https://github.com/omeed-maghzian/mtag/commit/86dfc4c57344816352256d531c1ad864ab8d827d). Now using `--args.use_beta_se` will ask MTAG to use the BETA/SE columns in the input GWAS sumstats.
