### ISSUE TITLE
assertion error 

### ISSUE THREAD

**Issue by andgan** [omeed-maghzian/mtag#25]
I get this assertion error and it is not clear what's the problem with my data:

```
Traceback (most recent call last):
  File "/home/mtag/mtag-master/mtag.py", line 1348, in <module>
    mtag(args)
  File "/home/mtag/mtag-master/mtag.py", line 1197, in mtag
    Zs , Ns ,Fs, res_temp, DATA = extract_gwas_sumstats(DATA,args)
  File "/home/mtag/mtag-master/mtag.py", line 520, in extract_gwas_sumstats
    assert Zs.shape[1] == Ns.shape[1] == Fs.shape[1]
AssertionError
```

**Comment by huilisabrina** [comment]
Hi @andgan ,

Could you check that there're no N/A values in your input sumstats (for all traits), in particular the columns for Z scores, sample sizes, and **allele frequency**?  

Also, do all of your input sumstats all have the Z, N, F columns present? `Zs, Ns, Fs` are matrices of the shape M x P where M is the number of SNPs present in all sumstats and P is the number of traits. 

Thanks,
Hui

**Comment by andgan** [comment]
Hi,
Is F allele frequency? Is that a mandatory column? I don’t have it but it didn’t return any error.
Thanks!
Cheers,

**Comment by huilisabrina** [comment]
Hi @andgan ,

Yes F is allele frequency. It is used for filtering rare variants and also un-standardizing the MTAG effect sizes. If you did not specify via the `eaf_name` option, the software will automatically searches for any of these strings `/MAF|FREQ|FRQ/`. This may be problematic if the sumstats do not contain any of those. It might help to read through the tutorials on the [wiki page](https://github.com/omeed-maghzian/mtag/wiki/Tutorial-1:-The-Basics).

Thanks,
Hui

**Comment by huilisabrina** [comment]
Hi @andgan ,

Just wanted to follow up and see if your issue has been resolved. If so, please feel free to close the issue. 

Thanks,
Hui

**Comment by piotyama** [comment]
Please advise on how you were able to solve for this error. I am getting a similar error for my analysis

**Here's a portion of my log file indicating the error:**

**Warning: The mean chi2 statistic of trait 2 is less 1.02 - MTAG estimates may be unstable.
Dropped 0 SNPs due to strand ambiguity, 34706 SNPs remain in intersection after merging trait1
Dropped 0 SNPs due to strand ambiguity, 34706 SNPs remain in intersection after merging trait2
... Merge of GWAS summary statistics complete. Number of SNPs:	 34706

Traceback (most recent call last):
  File "/Users/piotyama/mtag/mtag.py", line 1567, in <module>
    mtag(args)
  File "/Users/piotyama/mtag/mtag.py", line 1339, in mtag
    Zs , Ns ,Fs, res_temp, DATA, N_raw = extract_gwas_sumstats(DATA,args,list(np.arange(args.P)))
  File "/Users/piotyama/mtag/mtag.py", line 595, in extract_gwas_sumstats
    assert Zs.shape[1] == Ns.shape[1] == Fs.shape[1]
AssertionError
Analysis terminated from error at Tue Jul 23 16:24:38 2019
Total time elapsed: 1.38s**

**Comment by paturley** [comment]
I think this means that some of the entries in your z-stat, sample size, or
allele frequency columns may be non-numeric. Have you done careful QC on
your summary statistics first?

**Comment by piotyama** [comment]
> I think this means that some of the entries in your z-stat, sample size, or allele frequency columns may be non-numeric. Have you done careful QC on your summary statistics first?
> […](#)

Thanks for your response @paturley, I have double checked and I can't pick out anything that is amiss with my Z, N F columns. I did not however use munge_stats from ldsc to prepare my sumstats could that be it - the hidden gotchas?

Also, I don't think this should be a concern but I am working on a different species (glycine max). I am trying to get this tool to work for my analyses. Could that explain the error or do you agree with me that it shouldn't be a problem?

Thanks

**Comment by piotyama** [comment]
Hi @paturley, I was able to get past the assertion error - thanks for your help. All I did was get munge.py to run using my sumstats to generate new input sumstats. This does not keep p-values (for some reason) so I append my sumstats with p-values before running mtag.py again.

Everything seems to work just fine except my analysis is terminated from error. Here's my log file (find below). I am thinking this is because I am attempting to run the analysis using a non-human species and therefore my SNPs do not match whatever the program is designed to recognize. Have you had any folks dealing with other species use  mtag? I would love to glean from them any ideas on how they did it.

Log file excerpt.......................

**Conversion finished at Thu Jul 25 12:09:31 2019
Total time elapsed: 0.32s
'snpid'
Traceback (most recent call last):
  File "/Users/piotyama/mtag/mtag.py", line 1567, in <module>
    mtag(args)
  File "/Users/piotyama/mtag/mtag.py", line 1336, in mtag
    DATA_U, DATA, args = load_and_merge_data(args)
  File "/Users/piotyama/mtag/mtag.py", line 269, in load_and_merge_data
    GWAS_d[p], sumstats_format[p] = _perform_munge(args, GWAS_d[p], gwas_dat_gen, p)
  File "/Users/piotyama/mtag/mtag.py", line 163, in _perform_munge
    GWAS_df = GWAS_df.merge(munged_results, how='inner',left_on =args.snp_name,right_on='SNP',suffixes=('','_ss'))
  File "/Users/piotyama/anaconda2/envs/mtag/lib/python2.7/site-packages/pandas/core/frame.py", line 6868, in merge
    copy=copy, indicator=indicator, validate=validate)
  File "/Users/piotyama/anaconda2/envs/mtag/lib/python2.7/site-packages/pandas/core/reshape/merge.py", line 47, in merge
    validate=validate)
  File "/Users/piotyama/anaconda2/envs/mtag/lib/python2.7/site-packages/pandas/core/reshape/merge.py", line 529, in __init__
    self.join_names) = self._get_merge_keys()
  File "/Users/piotyama/anaconda2/envs/mtag/lib/python2.7/site-packages/pandas/core/reshape/merge.py", line 846, in _get_merge_keys
    left_keys.append(left._get_label_or_level_values(lk))
  File "/Users/piotyama/anaconda2/envs/mtag/lib/python2.7/site-packages/pandas/core/generic.py", line 1706, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'snpid'
Analysis terminated from error at Thu Jul 25 12:09:31 2019
Total time elapsed: 0.41s**

**Comment by paturley** [comment]
Hello,

MTAG runs LDSC at one step of the calculation, and I think that LDSC restricts the SNPs to 1kG SNPs. I wonder if that is related to the problem.

The only other case that I know of where someone use MTAG with a nonhuman genome was in a rice genome. They seemed to make it work by running LDSC separately and changing a line of the MTAG code. Check out issue #28 .

**Comment by piotyama** [comment]
> MTAG runs LDSC at one step of the calculation, and I think that LDSC restricts the SNPs to 1kG SNPs. I wonder if that is related to the problem.

I don't know if it is - I'm still thinking how best to test if indeed it is the reason for the error? 

As for using a nonhuman genome - great that someone got it to work for rice. Thanks for pointing out issue #28. I will be checking that out
