### ISSUE TITLE
5 cohort run meta-analysis so slow

### ISSUE THREAD

**Issue by YaoXueming** [omeed-maghzian/mtag#65]
hi
I run the meta-analysis using five cohort，but it did not run when run the final cohort，did the MTAG have cohort restriction？

**Comment by huilisabrina** [comment]
Hi @YaoXueming ,

Can you attach or send your log file? It'll be easier to understand what's the issue here. 

Thanks,
Hui

**Comment by YaoXueming** [comment]
Hi,Hui
thank for your timely reply，here is the log file.
[all-mtag.log](https://github.com/omeed-maghzian/mtag/files/2988992/all-mtag.log)


Thanks
Xueming Yao

**Comment by huilisabrina** [comment]
Hi @YaoXueming ,

From the log, there is nothing that indicates errors in your mtag run. It might be due to the constraint on your computer/servers' RAM (see this [post](https://www.quora.com/Can-Python-Pandas-handle-10-million-rows-What-are-some-useful-techniques-to-work-with-the-large-data-frames)). Based on the time stamps, munging for the first 4 traits did not take more than 4 mins. To check if this is the issue, you can maybe subset the 5th trait by randomly sampling the similar # of SNPs as the other traits, and see if it runs. 

Best,
Hui

**Comment by YaoXueming** [comment]
hello, Hui
It proved that you are right. After improving the RAM, I run the mtag successfully without errors.
THANK YOU SO MUCH ！

Best wishes
Xueming Yao

**Comment by huilisabrina** [comment]
Hi @YaoXueming ,

Great! Glad it works :) I'm going to close this issue for now. Feel free to open a new one if you run into other questions. 

Best,
Hui
