### ISSUE TITLE
Using MAF, since freq is not included in results

### ISSUE THREAD

**Issue by Lassana1** [omeed-maghzian/mtag#80]
Hi all,
         If the effect allele frequency is not present in my results, is there anyway to run MTAG? I only have MAF values.

**Comment by paturley** [comment]
You need to know the effect/reference allele in order to verify that you
are using the same effect allele for each data set. If you know the effect
allele for each data set, using the MAF instead of the EAF should be fine.
If you don't know the effect allele for any of the data sets, there isn't a
way to make MTAG work appropriately.

**Comment by Lassana1** [comment]
Hi Patrick, thanks so much! I am a bit confused. I am attaching some of my results here. It has a "minor.allele" column that points out if alleleA or B is the minor allele for each snp.
Can you take a look at my txt file and see if it is possible to use on MTAG?
[trait1.head.txt](https://github.com/omeed-maghzian/mtag/files/3703665/trait1.head.txt)

**Comment by Lassana1** [comment]
Thank you! I found in the documentation that alleleA was the effect allele.
